package com.mk.coffee.model;

public class Custom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.id
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_id
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    private Integer customId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.coffee
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    private Byte coffee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.milk
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    private Byte milk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.sugar
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    private Byte sugar;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public Custom(Integer id, Integer customId, Byte coffee, Byte milk, Byte sugar) {
        this.id = id;
        this.customId = customId;
        this.coffee = coffee;
        this.milk = milk;
        this.sugar = sugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public Custom() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.id
     *
     * @return the value of custom.id
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.id
     *
     * @param id the value for custom.id
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_id
     *
     * @return the value of custom.custom_id
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_id
     *
     * @param customId the value for custom.custom_id
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.coffee
     *
     * @return the value of custom.coffee
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public Byte getCoffee() {
        return coffee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.coffee
     *
     * @param coffee the value for custom.coffee
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public void setCoffee(Byte coffee) {
        this.coffee = coffee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.milk
     *
     * @return the value of custom.milk
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public Byte getMilk() {
        return milk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.milk
     *
     * @param milk the value for custom.milk
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public void setMilk(Byte milk) {
        this.milk = milk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.sugar
     *
     * @return the value of custom.sugar
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public Byte getSugar() {
        return sugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.sugar
     *
     * @param sugar the value for custom.sugar
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    public void setSugar(Byte sugar) {
        this.sugar = sugar;
    }
}