package com.mk.coffee.model;

public class EbeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebean.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebean.member_id
     *
     * @mbg.generated
     */
    private Long memberId;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    public EbeanKey(Integer id, Long memberId) {
        this.id = id;
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    public EbeanKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebean.id
     *
     * @return the value of ebean.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebean.id
     *
     * @param id the value for ebean.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebean.member_id
     *
     * @return the value of ebean.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebean.member_id
     *
     * @param memberId the value for ebean.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
}