package com.mk.coffee.model;

import java.util.Date;

public class LocalAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_auth.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_auth.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_auth.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_auth.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_auth.validity_day
     *
     * @mbg.generated
     */
    private Integer validityDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    public LocalAuth(Integer id, Long memberId, String token, Date createDate, Integer validityDay) {
        this.id = id;
        this.memberId = memberId;
        this.token = token;
        this.createDate = createDate;
        this.validityDay = validityDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_auth
     *
     * @mbg.generated
     */
    public LocalAuth() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_auth.id
     *
     * @return the value of local_auth.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_auth.id
     *
     * @param id the value for local_auth.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_auth.member_id
     *
     * @return the value of local_auth.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_auth.member_id
     *
     * @param memberId the value for local_auth.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_auth.token
     *
     * @return the value of local_auth.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_auth.token
     *
     * @param token the value for local_auth.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_auth.create_date
     *
     * @return the value of local_auth.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_auth.create_date
     *
     * @param createDate the value for local_auth.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_auth.validity_day
     *
     * @return the value of local_auth.validity_day
     *
     * @mbg.generated
     */
    public Integer getValidityDay() {
        return validityDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_auth.validity_day
     *
     * @param validityDay the value for local_auth.validity_day
     *
     * @mbg.generated
     */
    public void setValidityDay(Integer validityDay) {
        this.validityDay = validityDay;
    }
}