package com.mk.coffee.model;

import java.util.Date;

public class MemberCustomConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_custom_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_custom_config.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_custom_config.custom_config_id
     *
     * @mbg.generated
     */
    private Integer customConfigId;

    private CustomConfig customConfig;

    public CustomConfig getCustomConfig() {
        return customConfig;
    }

    public void setCustomConfig(CustomConfig customConfig) {
        this.customConfig = customConfig;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_custom_config.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_custom_config
     *
     * @mbg.generated
     */
    public MemberCustomConfig(Integer id, Long memberId, Integer customConfigId, Date createDate) {
        this.id = id;
        this.memberId = memberId;
        this.customConfigId = customConfigId;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_custom_config
     *
     * @mbg.generated
     */
    public MemberCustomConfig() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_custom_config.id
     *
     * @return the value of member_custom_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_custom_config.id
     *
     * @param id the value for member_custom_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_custom_config.member_id
     *
     * @return the value of member_custom_config.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_custom_config.member_id
     *
     * @param memberId the value for member_custom_config.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_custom_config.custom_config_id
     *
     * @return the value of member_custom_config.custom_config_id
     *
     * @mbg.generated
     */
    public Integer getCustomConfigId() {
        return customConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_custom_config.custom_config_id
     *
     * @param customConfigId the value for member_custom_config.custom_config_id
     *
     * @mbg.generated
     */
    public void setCustomConfigId(Integer customConfigId) {
        this.customConfigId = customConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_custom_config.create_date
     *
     * @return the value of member_custom_config.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_custom_config.create_date
     *
     * @param createDate the value for member_custom_config.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}