package com.mk.coffee.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProductConversionCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.conversion_code
     *
     * @mbg.generated
     */
    private String conversionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.order_details_id
     *
     * @mbg.generated
     */
    private String orderDetailsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.shopping_cart_id
     *
     * @mbg.generated
     */
    private Integer shoppingCartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    private Product product;

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.conversion_state
     *
     * @mbg.generated
     */
    private Integer conversionState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.crate_date
     *
     * @mbg.generated
     */
    private Date crateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_conversion_code.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    private Members members;

    public Members getMembers() {
        return members;
    }

    public void setMembers(Members members) {
        this.members = members;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_conversion_code
     *
     * @mbg.generated
     */
    public ProductConversionCode(Integer id, String conversionCode, String orderNum, String orderDetailsId, Integer shoppingCartId, Integer productId, Integer conversionState, Date crateDate, Date updateDate, Long memberId) {
        this.id = id;
        this.conversionCode = conversionCode;
        this.orderNum = orderNum;
        this.orderDetailsId = orderDetailsId;
        this.shoppingCartId = shoppingCartId;
        this.productId = productId;
        this.conversionState = conversionState;
        this.crateDate = crateDate;
        this.updateDate = updateDate;
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_conversion_code
     *
     * @mbg.generated
     */
    public ProductConversionCode() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.id
     *
     * @return the value of product_conversion_code.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.id
     *
     * @param id the value for product_conversion_code.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.conversion_code
     *
     * @return the value of product_conversion_code.conversion_code
     * @mbg.generated
     */
    public String getConversionCode() {
        return conversionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.conversion_code
     *
     * @param conversionCode the value for product_conversion_code.conversion_code
     * @mbg.generated
     */
    public void setConversionCode(String conversionCode) {
        this.conversionCode = conversionCode == null ? null : conversionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.order_num
     *
     * @return the value of product_conversion_code.order_num
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.order_num
     *
     * @param orderNum the value for product_conversion_code.order_num
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.order_details_id
     *
     * @return the value of product_conversion_code.order_details_id
     * @mbg.generated
     */
    public String getOrderDetailsId() {
        return orderDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.order_details_id
     *
     * @param orderDetailsId the value for product_conversion_code.order_details_id
     * @mbg.generated
     */
    public void setOrderDetailsId(String orderDetailsId) {
        this.orderDetailsId = orderDetailsId == null ? null : orderDetailsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.shopping_cart_id
     *
     * @return the value of product_conversion_code.shopping_cart_id
     * @mbg.generated
     */
    public Integer getShoppingCartId() {
        return shoppingCartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.shopping_cart_id
     *
     * @param shoppingCartId the value for product_conversion_code.shopping_cart_id
     * @mbg.generated
     */
    public void setShoppingCartId(Integer shoppingCartId) {
        this.shoppingCartId = shoppingCartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.product_id
     *
     * @return the value of product_conversion_code.product_id
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.product_id
     *
     * @param productId the value for product_conversion_code.product_id
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.conversion_state
     *
     * @return the value of product_conversion_code.conversion_state
     * @mbg.generated
     */
    public Integer getConversionState() {
        return conversionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.conversion_state
     *
     * @param conversionState the value for product_conversion_code.conversion_state
     * @mbg.generated
     */
    public void setConversionState(Integer conversionState) {
        this.conversionState = conversionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.crate_date
     *
     * @return the value of product_conversion_code.crate_date
     * @mbg.generated
     */
    public Date getCrateDate() {
        return crateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.crate_date
     *
     * @param crateDate the value for product_conversion_code.crate_date
     * @mbg.generated
     */
    public void setCrateDate(Date crateDate) {
        this.crateDate = crateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.update_date
     *
     * @return the value of product_conversion_code.update_date
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.update_date
     *
     * @param updateDate the value for product_conversion_code.update_date
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_conversion_code.member_id
     *
     * @return the value of product_conversion_code.member_id
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_conversion_code.member_id
     *
     * @param memberId the value for product_conversion_code.member_id
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
}