package com.mk.coffee.model;

import java.util.Date;

public class WxKeyword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_keyword.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_keyword.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_keyword.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    public WxKeyword(Integer id, String keyword, Date createDate) {
        this.id = id;
        this.keyword = keyword;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    public WxKeyword() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_keyword.id
     *
     * @return the value of wx_keyword.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_keyword.id
     *
     * @param id the value for wx_keyword.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_keyword.keyword
     *
     * @return the value of wx_keyword.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_keyword.keyword
     *
     * @param keyword the value for wx_keyword.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_keyword.create_date
     *
     * @return the value of wx_keyword.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_keyword.create_date
     *
     * @param createDate the value for wx_keyword.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}