package com.mk.coffee.mapper;

import com.mk.coffee.model.Activity;
import com.mk.coffee.model.ActivityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    long countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    int deleteByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Delete({
            "delete from activity",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Insert({
            "insert into activity (id, title, ",
            "sub_title, content, ",
            "type, wx_card_id, ",
            "create_date, start_time, ",
            "end_time, picture_url, ",
            "enter_url)",
            "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
            "#{subTitle,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
            "#{type,jdbcType=INTEGER}, #{wxCardId,jdbcType=VARCHAR}, ",
            "#{createDate,jdbcType=TIMESTAMP}, #{startTime,jdbcType=TIMESTAMP}, ",
            "#{endTime,jdbcType=TIMESTAMP}, #{pictureUrl,jdbcType=VARCHAR}, ",
            "#{enterUrl,jdbcType=VARCHAR})"
    })
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    List<Activity> selectByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, title, sub_title, content, type, wx_card_id, create_date, start_time, end_time, ",
            "picture_url, enter_url",
            "from activity",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.ActivityMapper.BaseResultMap")
    Activity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated
     */
    @Update({
            "update activity",
            "set title = #{title,jdbcType=VARCHAR},",
            "sub_title = #{subTitle,jdbcType=VARCHAR},",
            "content = #{content,jdbcType=VARCHAR},",
            "type = #{type,jdbcType=INTEGER},",
            "wx_card_id = #{wxCardId,jdbcType=VARCHAR},",
            "create_date = #{createDate,jdbcType=TIMESTAMP},",
            "start_time = #{startTime,jdbcType=TIMESTAMP},",
            "end_time = #{endTime,jdbcType=TIMESTAMP},",
            "picture_url = #{pictureUrl,jdbcType=VARCHAR},",
            "enter_url = #{enterUrl,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Activity record);

    @Select({
            "select",
            "id, title,sub_title, content, type,wx_card_id, create_date, start_time, end_time, picture_url,enter_url",
            "from activity",
            "where start_time< now() and end_time>now()"
    })
    List<Activity> getActivityList();
}