package com.mk.coffee.mapper;

import com.mk.coffee.model.CooperativePartnerCoffeeMachine;
import com.mk.coffee.model.CooperativePartnerCoffeeMachineExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CooperativePartnerCoffeeMachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    long countByExample(CooperativePartnerCoffeeMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    int deleteByExample(CooperativePartnerCoffeeMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    @Delete({
        "delete from cooperative_partner_coffee_machine",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    @Insert({
        "insert into cooperative_partner_coffee_machine (id, cooperativer_parther_id, ",
        "coffee_machine_id, create_date)",
        "values (#{id,jdbcType=INTEGER}, #{cooperativerPartherId,jdbcType=INTEGER}, ",
        "#{coffeeMachineId,jdbcType=INTEGER}, #{createDate,jdbcType=TIMESTAMP})"
    })
    int insert(CooperativePartnerCoffeeMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    int insertSelective(CooperativePartnerCoffeeMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    List<CooperativePartnerCoffeeMachine> selectByExample(CooperativePartnerCoffeeMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, cooperativer_parther_id, coffee_machine_id, create_date",
        "from cooperative_partner_coffee_machine",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.CooperativePartnerCoffeeMachineMapper.BaseResultMap")
    CooperativePartnerCoffeeMachine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CooperativePartnerCoffeeMachine record, @Param("example") CooperativePartnerCoffeeMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CooperativePartnerCoffeeMachine record, @Param("example") CooperativePartnerCoffeeMachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CooperativePartnerCoffeeMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_coffee_machine
     *
     * @mbg.generated
     */
    @Update({
        "update cooperative_partner_coffee_machine",
        "set cooperativer_parther_id = #{cooperativerPartherId,jdbcType=INTEGER},",
          "coffee_machine_id = #{coffeeMachineId,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CooperativePartnerCoffeeMachine record);
}