package com.mk.coffee.mapper;

import com.mk.coffee.model.CooperativePartner;
import com.mk.coffee.model.CooperativePartnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CooperativePartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    long countByExample(CooperativePartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    int deleteByExample(CooperativePartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    @Delete({
        "delete from cooperative_partner",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    @Insert({
        "insert into cooperative_partner (id, name, ",
        "password, address, ",
        "contacts, phone)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{contacts,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR})"
    })
    int insert(CooperativePartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    int insertSelective(CooperativePartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    List<CooperativePartner> selectByExample(CooperativePartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, password, address, contacts, phone",
        "from cooperative_partner",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.CooperativePartnerMapper.BaseResultMap")
    CooperativePartner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CooperativePartner record, @Param("example") CooperativePartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CooperativePartner record, @Param("example") CooperativePartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CooperativePartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner
     *
     * @mbg.generated
     */
    @Update({
        "update cooperative_partner",
        "set name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "contacts = #{contacts,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CooperativePartner record);
}