package com.mk.coffee.mapper;

import com.mk.coffee.model.CooperativePartnerProduct;
import com.mk.coffee.model.CooperativePartnerProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CooperativePartnerProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    long countByExample(CooperativePartnerProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    int deleteByExample(CooperativePartnerProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    @Delete({
        "delete from cooperative_partner_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    @Insert({
        "insert into cooperative_partner_product (id, product_id, ",
        "cooperative_partner_id, member_id, ",
        "create_date)",
        "values (#{id,jdbcType=INTEGER}, #{productId,jdbcType=INTEGER}, ",
        "#{cooperativePartnerId,jdbcType=INTEGER}, #{memberId,jdbcType=DECIMAL}, ",
        "#{createDate,jdbcType=TIMESTAMP})"
    })
    int insert(CooperativePartnerProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    int insertSelective(CooperativePartnerProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    List<CooperativePartnerProduct> selectByExample(CooperativePartnerProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, product_id, cooperative_partner_id, member_id, create_date",
        "from cooperative_partner_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.CooperativePartnerProductMapper.BaseResultMap")
    CooperativePartnerProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CooperativePartnerProduct record, @Param("example") CooperativePartnerProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CooperativePartnerProduct record, @Param("example") CooperativePartnerProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CooperativePartnerProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperative_partner_product
     *
     * @mbg.generated
     */
    @Update({
        "update cooperative_partner_product",
        "set product_id = #{productId,jdbcType=INTEGER},",
          "cooperative_partner_id = #{cooperativePartnerId,jdbcType=INTEGER},",
          "member_id = #{memberId,jdbcType=DECIMAL},",
          "create_date = #{createDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CooperativePartnerProduct record);
}