package com.mk.coffee.mapper;

import com.mk.coffee.model.CustomConfig;
import com.mk.coffee.model.CustomConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CustomConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    long countByExample(CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int deleteByExample(CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    @Delete({
        "delete from custom_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    @Insert({
        "insert into custom_config (id, name, ",
        "coffee, milk, sugar, ",
        "is_recommend, create_date, ",
        "coffee_name, milk_name, ",
        "sugar_name)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{coffee,jdbcType=INTEGER}, #{milk,jdbcType=INTEGER}, #{sugar,jdbcType=INTEGER}, ",
        "#{isRecommend,jdbcType=BIT}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{coffeeName,jdbcType=VARCHAR}, #{milkName,jdbcType=VARCHAR}, ",
        "#{sugarName,jdbcType=VARCHAR})"
    })
    int insert(CustomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int insertSelective(CustomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    List<CustomConfig> selectByExample(CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, coffee, milk, sugar, is_recommend, create_date, coffee_name, milk_name, ",
        "sugar_name",
        "from custom_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.CustomConfigMapper.BaseResultMap")
    CustomConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomConfig record, @Param("example") CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomConfig record, @Param("example") CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    @Update({
        "update custom_config",
        "set name = #{name,jdbcType=VARCHAR},",
          "coffee = #{coffee,jdbcType=INTEGER},",
          "milk = #{milk,jdbcType=INTEGER},",
          "sugar = #{sugar,jdbcType=INTEGER},",
          "is_recommend = #{isRecommend,jdbcType=BIT},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "coffee_name = #{coffeeName,jdbcType=VARCHAR},",
          "milk_name = #{milkName,jdbcType=VARCHAR},",
          "sugar_name = #{sugarName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CustomConfig record);


    CustomConfig getProductConfigByProductId(@Param("productId") int productId);
}