package com.mk.coffee.mapper;

import com.mk.coffee.model.CustomConfig;
import com.mk.coffee.model.CustomConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface CustomConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    long countByExample(CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int deleteByExample(CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    @Insert({
        "insert into custom_config (id, name, ",
        "coffee, milk, sugar)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{coffee,jdbcType=INTEGER}, #{milk,jdbcType=INTEGER}, #{sugar,jdbcType=INTEGER})"
    })
    int insert(CustomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int insertSelective(CustomConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    List<CustomConfig> selectByExample(CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomConfig record, @Param("example") CustomConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomConfig record, @Param("example") CustomConfigExample example);
}