package com.mk.coffee.mapper;

import com.mk.coffee.model.Custom;
import com.mk.coffee.model.CustomExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface CustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    long countByExample(CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    int deleteByExample(CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    @Insert({
        "insert into custom (id, custom_id, ",
        "coffee, milk, sugar)",
        "values (#{id,jdbcType=INTEGER}, #{customId,jdbcType=INTEGER}, ",
        "#{coffee,jdbcType=TINYINT}, #{milk,jdbcType=TINYINT}, #{sugar,jdbcType=TINYINT})"
    })
    int insert(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    int insertSelective(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    List<Custom> selectByExample(CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") Custom record, @Param("example") CustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbg.generated Mon Feb 27 11:49:17 CST 2017
     */
    int updateByExample(@Param("record") Custom record, @Param("example") CustomExample example);
}