package com.mk.coffee.mapper;

import com.mk.coffee.model.EbeanProduct;
import com.mk.coffee.model.EbeanProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EbeanProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    long countByExample(EbeanProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    int deleteByExample(EbeanProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ebean_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ebean_product (id, title, ",
        "e_num, giving_num, ",
        "money, create_date)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{eNum,jdbcType=INTEGER}, #{givingNum,jdbcType=INTEGER}, ",
        "#{money,jdbcType=REAL}, #{createDate,jdbcType=TIMESTAMP})"
    })
    int insert(EbeanProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    int insertSelective(EbeanProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    List<EbeanProduct> selectByExample(EbeanProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, title, e_num, giving_num, money, create_date",
        "from ebean_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.EbeanProductMapper.BaseResultMap")
    EbeanProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EbeanProduct record, @Param("example") EbeanProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EbeanProduct record, @Param("example") EbeanProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EbeanProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean_product
     *
     * @mbg.generated
     */
    @Update({
        "update ebean_product",
        "set title = #{title,jdbcType=VARCHAR},",
          "e_num = #{eNum,jdbcType=INTEGER},",
          "giving_num = #{givingNum,jdbcType=INTEGER},",
          "money = #{money,jdbcType=REAL},",
          "create_date = #{createDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EbeanProduct record);
}