package com.mk.coffee.mapper;

import com.mk.coffee.model.Ebean;
import com.mk.coffee.model.EbeanExample;
import com.mk.coffee.model.EbeanKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EbeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    long countByExample(EbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    int deleteByExample(EbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ebean",
        "where id = #{id,jdbcType=INTEGER}",
          "or member_id = #{memberId,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(EbeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ebean (id, member_id, ",
        "e_num, giving_num, ",
        "total_num, create_date, ",
        "update_date)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=DECIMAL}, ",
        "#{eNum,jdbcType=INTEGER}, #{givingNum,jdbcType=INTEGER}, ",
        "#{totalNum,jdbcType=INTEGER}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{updateDate,jdbcType=TIMESTAMP})"
    })
    int insert(Ebean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    int insertSelective(Ebean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    List<Ebean> selectByExample(EbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, e_num, giving_num, total_num, create_date, update_date",
        "from ebean",
        "where id = #{id,jdbcType=INTEGER}",
          "and member_id = #{memberId,jdbcType=DECIMAL}"
    })
    @ResultMap("com.mk.coffee.mapper.EbeanMapper.BaseResultMap")
    Ebean selectByPrimaryKey(EbeanKey key);


    @Select({
            "select",
            "id, member_id, e_num, giving_num, total_num, create_date, update_date",
            "from ebean",
            "where id = #{id,jdbcType=INTEGER}",
            "or member_id = #{memberId,jdbcType=DECIMAL}"
    })
    @ResultMap("com.mk.coffee.mapper.EbeanMapper.BaseResultMap")
    Ebean selectByOrPrimaryKey(EbeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ebean record, @Param("example") EbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ebean record, @Param("example") EbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ebean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebean
     *
     * @mbg.generated
     */
    @Update({
        "update ebean",
        "set e_num = #{eNum,jdbcType=INTEGER},",
          "giving_num = #{givingNum,jdbcType=INTEGER},",
          "total_num = #{totalNum,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}",
          "and member_id = #{memberId,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Ebean record);
}