package com.mk.coffee.mapper;

import com.mk.coffee.model.ErrorCode;
import com.mk.coffee.model.ErrorCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ErrorCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    long countByExample(ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    int deleteByExample(ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    @Delete({
        "delete from error_code",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    @Insert({
        "insert into error_code (id, code, ",
        "message)",
        "values (#{id,jdbcType=INTEGER}, #{code,jdbcType=VARCHAR}, ",
        "#{message,jdbcType=VARCHAR})"
    })
    int insert(ErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    int insertSelective(ErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    List<ErrorCode> selectByExample(ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    @Select({
        "select",
        "id, code, message",
        "from error_code",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.ErrorCodeMapper.BaseResultMap")
    ErrorCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") ErrorCode record, @Param("example") ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    int updateByExample(@Param("record") ErrorCode record, @Param("example") ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    int updateByPrimaryKeySelective(ErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated Mon Feb 27 15:34:27 CST 2017
     */
    @Update({
        "update error_code",
        "set code = #{code,jdbcType=VARCHAR},",
          "message = #{message,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ErrorCode record);
}