package com.mk.coffee.mapper;

import com.mk.coffee.model.MemberAddress;
import com.mk.coffee.model.MemberAddressExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MemberAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    long countByExample(MemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    int deleteByExample(MemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    @Delete({
            "delete from member_address",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    @Insert({
            "insert into member_address (id, member_id, ",
            "address_id, is_selected, ",
            "create_date)",
            "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=DECIMAL}, ",
            "#{addressId,jdbcType=INTEGER}, #{isSelected,jdbcType=BIT}, ",
            "#{createDate,jdbcType=TIMESTAMP})"
    })
    int insert(MemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    int insertSelective(MemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    List<MemberAddress> selectByExample(MemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, member_id, address_id, is_selected, create_date",
            "from member_address",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.MemberAddressMapper.BaseResultMap")
    MemberAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberAddress record, @Param("example") MemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberAddress record, @Param("example") MemberAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_address
     *
     * @mbg.generated
     */
    @Update({
            "update member_address",
            "set member_id = #{memberId,jdbcType=DECIMAL},",
            "address_id = #{addressId,jdbcType=INTEGER},",
            "is_selected = #{isSelected,jdbcType=BIT},",
            "create_date = #{createDate,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MemberAddress record);


    List<MemberAddress> getMemberAddressByMemberId(@Param("memberId") long memberId);

    MemberAddress getSelectedMemberAddress(@Param("memberId") long memberId);
}