package com.mk.coffee.mapper;

import com.mk.coffee.model.Oauth;
import com.mk.coffee.model.OauthExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    long countByExample(OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    int deleteByExample(OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    @Delete({
        "delete from o_auth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    @Insert({
        "insert into o_auth (id, member_id, ",
        "oauth_id, oauth_name, ",
        "oauth_access_token, oauth_expires)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=DECIMAL}, ",
        "#{oauthId,jdbcType=VARCHAR}, #{oauthName,jdbcType=VARCHAR}, ",
        "#{oauthAccessToken,jdbcType=VARCHAR}, #{oauthExpires,jdbcType=TIMESTAMP})"
    })
    int insert(Oauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    int insertSelective(Oauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    List<Oauth> selectByExample(OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, oauth_id, oauth_name, oauth_access_token, oauth_expires",
        "from o_auth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.OauthMapper.BaseResultMap")
    Oauth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Oauth record, @Param("example") OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Oauth record, @Param("example") OauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Oauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_auth
     *
     * @mbg.generated
     */
    @Update({
        "update o_auth",
        "set member_id = #{memberId,jdbcType=DECIMAL},",
          "oauth_id = #{oauthId,jdbcType=VARCHAR},",
          "oauth_name = #{oauthName,jdbcType=VARCHAR},",
          "oauth_access_token = #{oauthAccessToken,jdbcType=VARCHAR},",
          "oauth_expires = #{oauthExpires,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Oauth record);
}