package com.mk.coffee.mapper;

import com.mk.coffee.model.ProductToActivity;
import com.mk.coffee.model.ProductToActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ProductToActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    long countByExample(ProductToActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    int deleteByExample(ProductToActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    @Delete({
        "delete from product_to_activity",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    @Insert({
        "insert into product_to_activity (id, create_date, ",
        "product_id, activity_id)",
        "values (#{id,jdbcType=INTEGER}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{productId,jdbcType=INTEGER}, #{activityId,jdbcType=INTEGER})"
    })
    int insert(ProductToActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    int insertSelective(ProductToActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    List<ProductToActivity> selectByExample(ProductToActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, create_date, product_id, activity_id",
        "from product_to_activity",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.ProductToActivityMapper.BaseResultMap")
    ProductToActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductToActivity record, @Param("example") ProductToActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductToActivity record, @Param("example") ProductToActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductToActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_to_activity
     *
     * @mbg.generated
     */
    @Update({
        "update product_to_activity",
        "set create_date = #{createDate,jdbcType=TIMESTAMP},",
          "product_id = #{productId,jdbcType=INTEGER},",
          "activity_id = #{activityId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductToActivity record);
}