package com.mk.coffee.mapper;

import com.mk.coffee.model.RecoveryPicture;
import com.mk.coffee.model.RecoveryPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RecoveryPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    long countByExample(RecoveryPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    int deleteByExample(RecoveryPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    @Delete({
        "delete from recovery_picture",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    @Insert({
        "insert into recovery_picture (id, member_id, ",
        "picture_key, product_id)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=DECIMAL}, ",
        "#{pictureKey,jdbcType=VARCHAR}, #{productId,jdbcType=INTEGER})"
    })
    int insert(RecoveryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    int insertSelective(RecoveryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    List<RecoveryPicture> selectByExample(RecoveryPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, picture_key, product_id",
        "from recovery_picture",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.RecoveryPictureMapper.BaseResultMap")
    RecoveryPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RecoveryPicture record, @Param("example") RecoveryPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RecoveryPicture record, @Param("example") RecoveryPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RecoveryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recovery_picture
     *
     * @mbg.generated
     */
    @Update({
        "update recovery_picture",
        "set member_id = #{memberId,jdbcType=DECIMAL},",
          "picture_key = #{pictureKey,jdbcType=VARCHAR},",
          "product_id = #{productId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RecoveryPicture record);
}