package com.mk.coffee.mapper;

import com.mk.coffee.model.SysRole;
import com.mk.coffee.model.SysRoleExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    long countByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int deleteByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    @Delete({
            "delete from sys_role",
            "where role_id = #{roleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    @Insert({
            "insert into sys_role (role_id, role_name, ",
            "role_type, role_description, ",
            "create_id, create_date, ",
            "remark)",
            "values (#{roleId,jdbcType=INTEGER}, #{roleName,jdbcType=VARCHAR}, ",
            "#{roleType,jdbcType=INTEGER}, #{roleDescription,jdbcType=VARCHAR}, ",
            "#{createId,jdbcType=INTEGER}, #{createDate,jdbcType=TIMESTAMP}, ",
            "#{remark,jdbcType=VARCHAR})"
    })
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    List<SysRole> selectByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "role_id, role_name, role_type, role_description, create_id, create_date, remark",
            "from sys_role",
            "where role_id = #{roleId,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.SysRoleMapper.BaseResultMap")
    SysRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    @Update({
            "update sys_role",
            "set role_name = #{roleName,jdbcType=VARCHAR},",
            "role_type = #{roleType,jdbcType=INTEGER},",
            "role_description = #{roleDescription,jdbcType=VARCHAR},",
            "create_id = #{createId,jdbcType=INTEGER},",
            "create_date = #{createDate,jdbcType=TIMESTAMP},",
            "remark = #{remark,jdbcType=VARCHAR}",
            "where role_id = #{roleId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysRole record);

    List<SysRole> getSysRoles(@Param("userId") int userId);
}