package com.mk.coffee.mapper;

import com.mk.coffee.model.SysUserOrderDetails;
import com.mk.coffee.model.SysUserOrderDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysUserOrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    long countByExample(SysUserOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    int deleteByExample(SysUserOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sys_user_order_details",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sys_user_order_details (id, user_id, ",
        "coffee_machine_id, order_details_id, ",
        "state, contacts, ",
        "phone, address, ",
        "create_date, remark)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{coffeeMachineId,jdbcType=INTEGER}, #{orderDetailsId,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=VARCHAR}, #{contacts,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(SysUserOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    int insertSelective(SysUserOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    List<SysUserOrderDetails> selectByExample(SysUserOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user_id, coffee_machine_id, order_details_id, state, contacts, phone, address, ",
        "create_date, remark",
        "from sys_user_order_details",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.SysUserOrderDetailsMapper.BaseResultMap")
    SysUserOrderDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysUserOrderDetails record, @Param("example") SysUserOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysUserOrderDetails record, @Param("example") SysUserOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_order_details
     *
     * @mbg.generated
     */
    @Update({
        "update sys_user_order_details",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "coffee_machine_id = #{coffeeMachineId,jdbcType=INTEGER},",
          "order_details_id = #{orderDetailsId,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR},",
          "contacts = #{contacts,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysUserOrderDetails record);
}