package com.mk.coffee.mapper;

import com.mk.coffee.model.VerificationCode;
import com.mk.coffee.model.VerificationCodeExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface VerificationCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    long countByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    int deleteByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    @Delete({
            "delete from verification_code",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    @Insert({
            "insert into verification_code (id, code, ",
            "phone, create_date, ",
            "validity_minute, verify_state)",
            "values (#{id,jdbcType=INTEGER}, #{code,jdbcType=VARCHAR}, ",
            "#{phone,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
            "#{validityMinute,jdbcType=INTEGER}, #{verifyState,jdbcType=BIT})"
    })
    int insert(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    int insertSelective(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    List<VerificationCode> selectByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, code, phone, create_date, validity_minute, verify_state",
            "from verification_code",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.VerificationCodeMapper.BaseResultMap")
    VerificationCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VerificationCode record, @Param("example") VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VerificationCode record, @Param("example") VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated
     */
    @Update({
            "update verification_code",
            "set code = #{code,jdbcType=VARCHAR},",
            "phone = #{phone,jdbcType=VARCHAR},",
            "create_date = #{createDate,jdbcType=TIMESTAMP},",
            "validity_minute = #{validityMinute,jdbcType=INTEGER},",
            "verify_state = #{verifyState,jdbcType=BIT}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(VerificationCode record);

    @Select({
            "select",
            "id, code, phone, create_date, validity_minute,verify_state",
            "from verification_code",
            "where phone = #{phone,jdbcType=VARCHAR} order by create_date DESC"
    })
    //查询最近一条验证码
    @ResultMap("com.mk.coffee.mapper.VerificationCodeMapper.BaseResultMap")
    List<VerificationCode> selectCodesByPhoneOrderCreateDate(String phone);
}