package com.mk.coffee.mapper;

import com.mk.coffee.model.WxKeyword;
import com.mk.coffee.model.WxKeywordExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface WxKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    long countByExample(WxKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(WxKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    @Delete({
            "delete from wx_keyword",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    @Insert({
            "insert into wx_keyword (id, keyword, ",
            "create_date)",
            "values (#{id,jdbcType=INTEGER}, #{keyword,jdbcType=VARCHAR}, ",
            "#{createDate,jdbcType=TIMESTAMP})"
    })
    int insert(WxKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    int insertSelective(WxKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    List<WxKeyword> selectByExample(WxKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, keyword, create_date",
            "from wx_keyword",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mk.coffee.mapper.WxKeywordMapper.BaseResultMap")
    WxKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxKeyword record, @Param("example") WxKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxKeyword record, @Param("example") WxKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_keyword
     *
     * @mbg.generated
     */
    @Update({
            "update wx_keyword",
            "set keyword = #{keyword,jdbcType=VARCHAR},",
            "create_date = #{createDate,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WxKeyword record);


    List<WxKeyword> getWxKeywordByKeyword(@Param("keyword") String keyword);
}